id: D080C882A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:00:10+00:00'
last_modified: '2022-05-27T15:58:34.362346+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    43bb:
      image_group_id: I1PD95910
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: 43bb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
