id: P64FB957D
initial_creation_type: ocr
source_metadata:
  volumes:
    af05948f5c6d427fa3521992b85f1148:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
